# Generated by Django 2.2.4 on 2019-08-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190809_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='senha',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
    ]
